// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6jn4rOhT5Jgdq8d1DKh_O566IdI9JWeA',
    appId: '1:372016180983:web:ac0a76aa3789431b622df2',
    messagingSenderId: '372016180983',
    projectId: 'project-water-f2424',
    authDomain: 'project-water-f2424.firebaseapp.com',
    storageBucket: 'project-water-f2424.appspot.com',
    measurementId: 'G-VNMRB8L660',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtxky4A4VMUtrmhZwLPWnCn-kvnSOjwYE',
    appId: '1:372016180983:android:f8af9f2995ca1743622df2',
    messagingSenderId: '372016180983',
    projectId: 'project-water-f2424',
    storageBucket: 'project-water-f2424.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJkLwG6X4kVROIEHmmmd2ojCjwc3NxI44',
    appId: '1:372016180983:ios:b8d00994eadbb71b622df2',
    messagingSenderId: '372016180983',
    projectId: 'project-water-f2424',
    storageBucket: 'project-water-f2424.appspot.com',
    iosBundleId: 'com.example.waterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJkLwG6X4kVROIEHmmmd2ojCjwc3NxI44',
    appId: '1:372016180983:ios:69c0b730a3789600622df2',
    messagingSenderId: '372016180983',
    projectId: 'project-water-f2424',
    storageBucket: 'project-water-f2424.appspot.com',
    iosBundleId: 'com.example.waterapp.RunnerTests',
  );
}
